// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package whats

import (
	"whatsm/api/whats"
)

type ControllerV1 struct{}

func NewV1() whats.IWhatsV1 {
	return &ControllerV1{}
}
